(in-package #:gsicr)

(defun usage ()
  (format t "~%Group Scholar Intro Call Registry~%~%")
  (format t "Commands:\n")
  (format t "  init-db                     Create schema and tables\n")
  (format t "  seed                        Insert sample records\n")
  (format t "  add --scholar NAME --partner ORG --call-date YYYY-MM-DD --outcome OUTCOME [--follow-up YYYY-MM-DD] [--notes TEXT]\n")
  (format t "  list [--limit N]\n")
  (format t "  summary\n")
  (format t "  partner-summary [--limit N]\n")
  (format t "  follow-ups [--days N]\n")
  (format t "\nEnvironment variables:\n")
  (format t "  GSICR_DB_HOST, GSICR_DB_PORT, GSICR_DB_NAME, GSICR_DB_USER, GSICR_DB_PASSWORD\n")
  (format t "  GSICR_DB_SCHEMA (default gs_intro_call_registry), GSICR_DB_SSLMODE (default disable)\n"))

(defun parse-args (args)
  (let ((command (first args))
        (options (make-hash-table :test #'equal))
        (remaining (rest args)))
    (when (or (null command) (string= command "--help") (string= command "-h"))
      (return-from parse-args (values "help" options)))
    (when (oddp (length remaining))
      (error "Options must be key/value pairs."))
    (loop for (key value) on remaining by #'cddr do
      (unless (and key (uiop:string-prefix-p "--" key))
        (error "Invalid option key: ~a" key))
      (setf (gethash key options) value))
    (values command options)))

(defun option (options key &optional default)
  (or (gethash key options) default))

(defun print-list (rows)
  (format t "~%ID | Scholar | Partner | Call Date | Outcome | Follow Up | Notes~%")
  (format t "------------------------------------------------------------------------~%")
  (dolist (row rows)
    (destructuring-bind (id scholar partner call-date outcome follow-up notes) row
      (format t "~a | ~a | ~a | ~a | ~a | ~a | ~a~%"
              id scholar partner call-date outcome (or follow-up "-") (or notes "-")))))

(defun print-summary (rows)
  (format t "~%Outcome | Total | Last Call~%")
  (format t "---------------------------~%")
  (dolist (row rows)
    (destructuring-bind (outcome total last-call) row
      (format t "~a | ~a | ~a~%" outcome total last-call))))

(defun print-follow-ups (rows)
  (format t "~%Scholar | Partner | Follow Up Date | Outcome~%")
  (format t "--------------------------------------------~%")
  (dolist (row rows)
    (destructuring-bind (scholar partner follow-up outcome) row
      (format t "~a | ~a | ~a | ~a~%" scholar partner follow-up outcome))))

(defun print-partner-summary (rows)
  (format t "~%Partner | Total | Attended | Converted | No-Show | Last Call | Next Follow Up~%")
  (format t "--------------------------------------------------------------------------------~%")
  (dolist (row rows)
    (destructuring-bind (partner total attended converted no-show last-call next-follow-up) row
      (format t "~a | ~a | ~a | ~a | ~a | ~a | ~a~%"
              partner total attended converted no-show last-call (or next-follow-up "-")))))

(defun handle-command (command options)
  (let ((cfg (load-db-config)))
    (cond
      ((string= command "init-db")
       (init-db cfg)
       (format t "Initialized schema and tables.~%"))
      ((string= command "seed")
       (seed-data cfg)
       (format t "Seeded sample intro call records.~%"))
      ((string= command "add")
       (let* ((scholar (option options "--scholar"))
              (partner (option options "--partner"))
              (call-date (option options "--call-date"))
              (outcome (option options "--outcome"))
              (follow-up (option options "--follow-up"))
              (notes (option options "--notes")))
         (dolist (required (list scholar partner call-date outcome))
           (when (or (null required) (string= required ""))
             (error "Missing required add options.")))
         (let ((id (add-intro-call cfg scholar partner call-date outcome follow-up notes)))
           (format t "Added intro call with id ~a.~%" id))))
      ((string= command "list")
       (let* ((limit (parse-integer (option options "--limit" "25"))))
         (print-list (list-intro-calls cfg limit))))
      ((string= command "summary")
       (print-summary (summarize-intro-calls cfg)))
      ((string= command "partner-summary")
       (let* ((limit (parse-integer (option options "--limit" "20"))))
         (print-partner-summary (partner-summary cfg limit))))
      ((string= command "follow-ups")
       (let ((days (parse-integer (option options "--days" "14"))))
         (print-follow-ups (upcoming-follow-ups cfg days))))
      ((string= command "help")
       (usage))
      (t (error "Unknown command: ~a" command)))))
